In [30]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)

In [31]:
df = pd.read_csv("trials.csv")
df.isna().sum()

year              931
decade              0
century             0
tried               0
deaths           3826
city             5213
gadm.adm2        1047
gadm.adm1         159
gadm.adm0           0
lon              5803
lat              5803
record.source       0
dtype: int64

In [ ]:
df_non_nan = df.dropna()
df_non_nan.head(500)

In [35]:
#df["gadm.adm0"=="France"]
df.loc[df['gadm.adm0'] == 'France']
# COMMUNE, DEPARTEMENT, REGION, COUNTRY
# Municipality, District, Region, Country

,year,decade,century,tried,deaths,city,gadm.adm2,gadm.adm1,gadm.adm0,lon,lat,record.source
1869,NaN,1570,1500,15,NaN,Saint-Die,Vosges,Lorraine,France,6.94777,48.2875,Briggs (2007)
1870,NaN,1570,1500,3,NaN,Blamont,Meurthe-et-Moselle,Lorraine,France,6.84384,48.5894,Briggs (2007)
1871,NaN,1570,1500,1,NaN,Gondreville,Meurthe-et-Moselle,Lorraine,France,5.96373,48.6931,Briggs (2007)
1872,NaN,1570,1500,1,NaN,Einville-au-jard,Meurthe-et-Moselle,Lorraine,France,6.48818,48.6551,Briggs (2007)
1873,NaN,1570,1500,2,NaN,Mirecourt,Vosges,Lorraine,France,6.13386,48.3022,Briggs (2007)
...,...,...,...,...,...,...,...,...,...,...,...,...
8929,NaN,1610,1600,44,10.0,NaN,NaN,Haute-Normandie,France,NaN,NaN,Monter (1997)
8930,NaN,1620,1600,12,4.0,NaN,NaN,Haute-Normandie,France,NaN,NaN,Monter (1997)
8931,NaN,1630,1600,12,NaN,NaN,NaN,Haute-Normandie,France,NaN,NaN,Monter (1997)
8932,NaN,1640,1600,6,NaN,NaN,NaN,Haute-Normandie,France,NaN,NaN,Monter (1997)
8933,NaN,1650,1600,6,0.0,NaN,NaN,Haute-Normandie,France,NaN,NaN,Monter (1997)